title: Embark
subtitle: "A simple & powerful framework for decentralized applications"
description: "Embark is a simple & powerful framework for decentralized applications"
author: Embark
language: en
timezone: UTC

url: https://embark.status.im
root: /
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
per_page: 0

theme: navy
deploy:
  type: git
  repo: git@github.com:hexojs/hexojs.github.io.git

highlight:
  enable: true
  line_number: false

disqus_shortname: hexojs
google_analytics: UA-48498357-3
fb_admins: 100000247608790
algolia:
  en:
    apiKey: 439d8dc2add18007a2f31be4a9c0ed70
    indexName: embark
twitter: iurimatias
github: embark-framework/embark
